import { useEffect, useMemo, useState } from 'react';
import { getJson, postJson } from './api';
import DocumentsPanel from './components/DocumentsPanel';
import SummaryPanel from './components/SummaryPanel';
import ChatPanel from './components/ChatPanel';

const DEFAULT_CHAT = [
  { role: 'bot', text: 'Upload a document. Once analyzed, ask specific legal questions or compare clauses here.' }
];

export default function App() {
  // --- STATE ---
  const [uploadedDocuments, setUploadedDocuments] = useState([]);
  const [selectedFiles, setSelectedFiles] = useState([]);
  const [uploadStatus, setUploadStatus] = useState('No documents uploaded yet.');
  const [activeDocument, setActiveDocument] = useState('No document selected');
  
  // NEW: Store the automatic summaries generated by the backend
  const [documentSummaries, setDocumentSummaries] = useState({});
  
  // Summary Panel State
  const [summary, setSummary] = useState('Upload documents to view the summary.');
  const [importantPoints, setImportantPoints] = useState([]);
  const [riskScore, setRiskScore] = useState('--');
  
  const [isUploading, setIsUploading] = useState(false);
  const [chatLog, setChatLog] = useState(DEFAULT_CHAT);

  // --- INITIAL LOAD ---
  useEffect(() => {
    const loadStatus = async () => {
      try {
        const status = await getJson('/api/status');
        setUploadedDocuments(status.uploadedDocuments || []);
      } catch (err) {
        console.error("Error fetching status:", err);
        // Keep defaults
      }
    };
    loadStatus();
  }, []);

  // --- AUTO-UPDATE SUMMARY PANEL ---
  // When the active document changes, pull its summary from our saved state
  useEffect(() => {
    if (activeDocument === 'All Documents') {
      setSummary('Comparison Mode Active. Use the chat box to ask how these documents differ.');
      setImportantPoints(['Ready for side-by-side comparison.']);
      setRiskScore('--');
    } else if (documentSummaries[activeDocument]) {
      // Extract the JSON data we saved during upload
      const docData = documentSummaries[activeDocument].answer || {};
      
      setSummary(docData.summary || docData.final_answer || 'Analysis complete.');
      
      // Pull risks and key clauses out of the JSON
      const formattedRisks = (docData.risks || []).map(r => `⚠️ ${r.title || r.risk} (${r.severity})`);
      const formattedClauses = (docData.key_clauses || []).map(c => `📄 ${c.clause_title}`);
      
      const merged = [...formattedRisks, ...formattedClauses];
      setImportantPoints(merged.length > 0 ? merged : ['No critical points detected.']);
      
      // We don't use a numerical score anymore, but we can count the High risks
      const highRisks = (docData.risks || []).filter(r => r.severity?.toLowerCase() === 'high').length;
      setRiskScore(highRisks > 0 ? 'High Risk' : 'Standard');
      
    } else {
      setSummary(`No summary available for ${activeDocument}.`);
      setImportantPoints([]);
      setRiskScore('--');
    }
  }, [activeDocument, documentSummaries]);

  const documentCountLabel = useMemo(() => {
    if (uploadedDocuments.length === 0) return 'No files loaded';
    if (uploadedDocuments.length === 1) return '1 file loaded';
    return `${uploadedDocuments.length} files loaded`;
  }, [uploadedDocuments]);

  // --- HANDLERS ---
  const handleUpload = async () => {
    if (selectedFiles.length === 0) {
      setUploadStatus('Choose one or more documents first.');
      return;
    }

    const formData = new FormData();
    selectedFiles.forEach((file) => formData.append('files', file));

    setIsUploading(true);
    setUploadStatus('Uploading and running legal analysis...');

    try {
      // Using standard fetch with FormData
      const response = await fetch('/api/upload', {
        method: 'POST',
        body: formData
      });
      const data = await response.json();
      
      if (!response.ok) throw new Error(data.detail || 'Upload failed');

      setUploadedDocuments(data.uploadedDocuments || []);
      
      // NEW: Save the summaries generated by the backend!
      if (data.summaries) {
        setDocumentSummaries(prev => ({ ...prev, ...data.summaries }));
      }

      setActiveDocument(data.uploadedDocuments[0] || 'Uploaded document');
      setUploadStatus(`${data.uploaded} document(s) successfully analyzed.`);
      setSelectedFiles([]);
      setChatLog(DEFAULT_CHAT);
      
    } catch (error) {
      setUploadStatus(error.message);
    } finally {
      setIsUploading(false);
    }
  };

  const handleReset = async () => {
    try {
      await postJson('/api/reset', {});
      setUploadedDocuments([]);
      setSelectedFiles([]);
      setDocumentSummaries({});
      setUploadStatus('Workspace reset.');
      setActiveDocument('No document selected');
      setSummary('Upload documents to view the summary.');
      setImportantPoints([]);
      setRiskScore('--');
      setChatLog(DEFAULT_CHAT);
    } catch (error) {
      setUploadStatus(error.message);
    }
  };

  // NEW: Handles routing to either Query or Compare endpoints
  const handleSendMessage = async (message, isCompareMode) => {
    if (!message.trim()) return;

    const newChatLog = [...chatLog, { role: 'user', text: message }];
    setChatLog(newChatLog);

    try {
      let responseData;

      if (isCompareMode || activeDocument === 'All Documents') {
        if (uploadedDocuments.length < 2) {
          throw new Error("Comparison requires 2 uploaded documents.");
        }
        // Route to the new Compare Endpoint
        responseData = await postJson('/api/compare', { 
          query: message,
          file_a: uploadedDocuments[0],
          file_b: uploadedDocuments[1]
        });
      } else {
        // Route to the new Query Endpoint
        responseData = await postJson('/api/query', { 
          query: message, 
          target_file: activeDocument 
        });
      }

      // The new backend returns data inside { ok: true, data: { answer: {...} } }
      const aiAnswer = responseData.data?.answer || responseData.answer || { final_answer: "No response." };
      
      setChatLog([...newChatLog, { role: 'bot', text: aiAnswer }]);

    } catch (error) {
      setChatLog([...newChatLog, { role: 'bot', text: error.message }]);
    }
  };

  return (
    <main className="dashboard">
      <DocumentsPanel
        uploadedDocuments={uploadedDocuments}
        selectedFiles={selectedFiles}
        setSelectedFiles={setSelectedFiles}
        uploadStatus={uploadStatus}
        activeDocument={activeDocument}
        setActiveDocument={setActiveDocument}
        documentCountLabel={documentCountLabel}
        onUpload={handleUpload}
        onReset={handleReset}
        isUploading={isUploading}
      />

      {/* Note: We removed the onAnalyze trigger because it happens automatically now! */}
      <SummaryPanel
        activeDocument={activeDocument}
        summary={summary}
        importantPoints={importantPoints}
        analysisNotes={['Analysis generated automatically upon upload.']}
        riskScore={riskScore}
        isAnalyzing={isUploading} 
      />

      <ChatPanel 
        chatLog={chatLog} 
        onSendMessage={handleSendMessage} 
        activeDocument={activeDocument} 
        allDocuments={uploadedDocuments}
      />
    </main>
  );
}